import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { BulletList, FaqList, StatusBadge } from "@/components/content-sections";
import { type CaseStudy, type Industry, type Locale, type Service, businessScenarios, industryEnrichment, industries, serviceEnrichment, services, text } from "@/lib/content-data";
import { JsonLd } from "@/components/json-ld";
import { pageBreadcrumbJsonLd } from "@/lib/seo-data";
import { siteUrl } from "@/lib/site-data";

export function SolutionDetail({ item, locale }: { item: Service; locale: Locale }) {
  const extra = serviceEnrichment[item.slug];
  const relatedIndustries = industries.filter((entry) => extra.industrySlugs.includes(entry.slug));
  const relatedScenarios = businessScenarios.filter((entry) => entry.goalSlugs.includes(item.slug));
  const path = `/solutions/${item.slug}`;
  const jsonLd = [{ ...pageBreadcrumbJsonLd(text(item.title, locale), path) }, { "@context": "https://schema.org", "@type": "Service", "@id": `${siteUrl}${path}/#service`, name: text(item.title, locale), description: text(item.problem, locale), provider: { "@id": `${siteUrl}/#organization` }, url: `${siteUrl}${path}/` }];
  return <main><JsonLd data={jsonLd} /><section className="light-band border-b border-slate-200 py-16 md:py-20"><div className="section-wrap max-w-4xl"><p className="kicker">{locale === "zh" ? "按业务目标" : "BUSINESS GOAL"}</p><h1 className="mt-5 text-balance text-4xl font-black text-navy-950 md:text-6xl">{text(item.title, locale)}</h1><p className="mt-6 text-lg leading-9 text-slate-600">{text(extra.summary, locale)}</p><p className="mt-4 text-sm leading-7 text-slate-600">{text(item.audience, locale)}</p></div></section><section className="section-wrap grid gap-8 py-14 md:grid-cols-2"><div><h2 className="text-2xl font-black text-navy-950">{locale === "zh" ? "常见业务问题" : "Common business problems"}</h2><div className="mt-5"><BulletList items={extra.commonProblems.map((entry) => text(entry, locale))} /></div></div><div><h2 className="text-2xl font-black text-navy-950">{locale === "zh" ? "可交付成果示例" : "Example deliverables"}</h2><div className="mt-5"><BulletList items={item.deliverables.map((entry) => text(entry, locale))} /></div></div></section><section className="light-band py-14"><div className="section-wrap grid gap-8 md:grid-cols-2"><div><h2 className="text-2xl font-black text-navy-950">{locale === "zh" ? "相关行业" : "Related industries"}</h2><div className="mt-5 flex flex-wrap gap-2">{relatedIndustries.map((entry) => <Link href={`/industries/${entry.slug}`} key={entry.slug} className="rounded-full border border-slate-200 px-3 py-2 text-sm font-black text-slate-700">{text(entry.title, locale)}</Link>)}</div></div><div><h2 className="text-2xl font-black text-navy-950">{locale === "zh" ? "相关典型场景" : "Related scenarios"}</h2><div className="mt-5 flex flex-wrap gap-2">{relatedScenarios.map((entry) => <Link href="/scenarios" key={entry.slug} className="rounded-full border border-blue-100 px-3 py-2 text-sm font-black text-vector-blue">{text(entry.title, locale)}</Link>)}</div></div></div></section><section className="section-wrap py-14"><h2 className="text-2xl font-black text-navy-950">{locale === "zh" ? "方法与边界" : "Method and boundaries"}</h2><div className="mt-5"><BulletList items={extra.process.map((entry) => text(entry, locale))} /></div><p className="mt-5 text-sm leading-7 text-slate-600">{text(item.boundary, locale)}</p><Link href="/delivery-process" className="button-primary mt-8">{locale === "zh" ? "不确定从哪里开始？了解交付方式" : "Not sure where to start? Explore delivery"}<ArrowRight size={16} /></Link></section></main>;
}

export function IndustryDetail({ item, locale }: { item: Industry; locale: Locale }) {
  const relatedServices = services.filter((service) => item.serviceSlugs.includes(service.slug));
  const extra = industryEnrichment[item.slug];
  const relatedScenarios = businessScenarios.filter((entry) => entry.industrySlugs.includes(item.slug));
  const path = `/industries/${item.slug}`;
  return <main><JsonLd data={pageBreadcrumbJsonLd(text(item.title, locale), path)} /><section className="light-band border-b border-slate-200 py-16 md:py-20"><div className="section-wrap max-w-4xl"><p className="kicker">{locale === "zh" ? "按行业" : "INDUSTRY"}</p><h1 className="mt-5 text-balance text-4xl font-black text-navy-950 md:text-6xl">{text(item.title, locale)}</h1><p className="mt-6 text-lg leading-9 text-slate-600">{text(extra.background, locale)}</p></div></section><section className="section-wrap grid gap-8 py-14 md:grid-cols-2"><div><h2 className="text-2xl font-black text-navy-950">{locale === "zh" ? "典型问题" : "Typical problems"}</h2><div className="mt-5"><BulletList items={extra.commonProblems.map((entry) => text(entry, locale))} /></div></div><div><h2 className="text-2xl font-black text-navy-950">{locale === "zh" ? "适配业务目标" : "Relevant business goals"}</h2><div className="mt-5 flex flex-wrap gap-2">{relatedServices.map((service) => <Link href={`/solutions/${service.slug}`} key={service.slug} className="rounded-full border border-blue-100 px-3 py-2 text-sm font-black text-vector-blue">{text(service.title, locale)}</Link>)}</div></div></section><section className="light-band py-14"><div className="section-wrap"><h2 className="text-2xl font-black text-navy-950">{locale === "zh" ? "相关典型场景" : "Related scenarios"}</h2><div className="mt-5 flex flex-wrap gap-2">{relatedScenarios.map((entry) => <Link href="/scenarios" key={entry.slug} className="rounded-full border border-slate-200 px-3 py-2 text-sm font-black text-slate-700">{text(entry.title, locale)}</Link>)}</div><Link href="/scenarios" className="mt-5 inline-block text-sm font-black text-vector-blue">{locale === "zh" ? "查看全部典型场景" : "View all scenarios"}</Link></div></section><section className="section-wrap py-14"><h2 className="text-2xl font-black text-navy-950">{locale === "zh" ? "资料与范围考虑" : "Materials and scope considerations"}</h2><div className="mt-5 grid gap-8 md:grid-cols-2"><BulletList items={extra.requiredMaterials.map((entry) => text(entry, locale))} /><BulletList items={item.risks.map((entry) => text(entry, locale))} /></div></section></main>;
}

export function CaseDetail({ item, locale }: { item: CaseStudy; locale: Locale }) {
  const path = `/work/${item.slug}`;
  const jsonLd = [{ ...pageBreadcrumbJsonLd(text(item.title, locale), path) }, { "@context": "https://schema.org", "@type": "CreativeWork", name: text(item.title, locale), description: text(item.background, locale), url: `${siteUrl}${path}/`, additionalType: `https://schema.org/${item.status === "pilot" ? "Project" : "CreativeWork"}` }];
  return <main><JsonLd data={jsonLd} /><section className="light-band border-b border-slate-200 py-16 md:py-20"><div className="section-wrap max-w-4xl"><StatusBadge status={item.status} locale={locale} slug={item.slug} /><h1 className="mt-5 text-balance text-4xl font-black text-navy-950 md:text-6xl">{text(item.title, locale)}</h1><p className="mt-6 text-lg leading-9 text-slate-600">{text(item.background, locale)}</p></div></section><section className="section-wrap grid gap-8 py-14 md:grid-cols-2"><div><h2 className="text-2xl font-black text-navy-950">{locale === "zh" ? "业务问题与目标" : "Business problem and objective"}</h2><p className="mt-4 text-sm leading-7 text-slate-600">{text(item.problem, locale)}</p><p className="mt-4 text-sm leading-7 text-slate-600">{text(item.objective, locale)}</p></div><div><h2 className="text-2xl font-black text-navy-950">{locale === "zh" ? "概念交付物" : "Concept deliverables"}</h2><div className="mt-4"><BulletList items={[...item.implementation, ...item.deliverables].map((entry) => text(entry, locale))} /></div></div></section><section className="light-band py-14"><div className="section-wrap grid gap-6 md:grid-cols-2"><article className="surface rounded-lg p-6"><h2 className="text-xl font-black text-navy-950">{locale === "zh" ? "方案说明" : "Proposal note"}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{text(item.result, locale)}</p></article><article className="surface rounded-lg p-6"><h2 className="text-xl font-black text-navy-950">{locale === "zh" ? "资料边界与延伸阅读" : "Material boundary and next reading"}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{text(item.confidentiality, locale)}</p><p className="mt-3 text-sm leading-7 text-slate-600">{text(item.nextStep, locale)}</p></article></div></section><section className="section-wrap py-14"><Link href="/delivery-process" className="button-primary">{locale === "zh" ? "了解交付方式" : "Explore delivery"}<ArrowRight size={16} /></Link></section></main>;
}
