export type Locale = "zh" | "en";
export type LocalizedText = { zh: string; en: string };
export type CaseStatus = "live" | "in-development" | "pilot" | "demo" | "concept";

export type Service = {
  slug: string;
  title: LocalizedText;
  audience: LocalizedText;
  problem: LocalizedText;
  deliverables: LocalizedText[];
  boundary: LocalizedText;
};

export type Industry = {
  slug: string;
  title: LocalizedText;
  summary: LocalizedText;
  scenarios: LocalizedText[];
  risks: LocalizedText[];
  serviceSlugs: string[];
};

export type BusinessGoal = Service & {
  id: string;
  summary: LocalizedText;
  customerProblems: LocalizedText[];
  outcomeDirections: LocalizedText[];
  featured: boolean;
  industrySlugs: string[];
  scenarioSlugs: string[];
};

export type BusinessScenario = {
  id: string;
  slug: string;
  title: LocalizedText;
  summary: LocalizedText;
  customerProblems: LocalizedText[];
  deliverables: LocalizedText[];
  goalSlugs: string[];
  industrySlugs: string[];
  featured: boolean;
};

export type CaseStudy = {
  slug: string;
  title: LocalizedText;
  status: CaseStatus;
  background: LocalizedText;
  problem: LocalizedText;
  objective: LocalizedText;
  implementation: LocalizedText[];
  deliverables: LocalizedText[];
  result: LocalizedText;
  nextStep: LocalizedText;
  confidentiality: LocalizedText;
  serviceSlugs: string[];
};

export type FAQItem = { id: string; category: LocalizedText; question: LocalizedText; answer: LocalizedText };
export type DeliveryStep = { number: string; title: LocalizedText; clientInput: LocalizedText; responsibility: LocalizedText; output: LocalizedText; acceptance: LocalizedText; risk: LocalizedText };

export const text = (value: LocalizedText, locale: Locale) => value[locale];

export type ServiceEnrichment = {
  summary: LocalizedText;
  commonProblems: LocalizedText[];
  process: LocalizedText[];
  industrySlugs: string[];
};
export type IndustryEnrichment = {
  background: LocalizedText;
  commonProblems: LocalizedText[];
  requiredMaterials: LocalizedText[];
  caseSlugs: string[];
};

export const services: Service[] = [
  { slug: "websites-portals", title: { zh: "企业网站与数字化门户", en: "Business Websites & Digital Portals" }, audience: { zh: "需要获客、展示、招商或客户入口的组织", en: "Organizations that need a clearer acquisition, presentation or client entry point" }, problem: { zh: "官网陈旧、信息分散、咨询路径不清", en: "An outdated site, scattered information or an unclear inquiry path" }, deliverables: [{ zh: "信息架构与页面", en: "Information architecture and pages" }, { zh: "多语内容与 SEO/GEO 基线", en: "Multilingual content and SEO/GEO baseline" }, { zh: "数字化门户规划", en: "Digital portal planning" }], boundary: { zh: "周期、上线方式、后台与数据范围需评估确认。", en: "Timeline, launch approach, admin and data scope require assessment." } },
  { slug: "business-systems", title: { zh: "企业业务系统定制", en: "Custom Business Systems" }, audience: { zh: "依赖表格、重复录入或跨部门协同的团队", en: "Teams relying on spreadsheets, repeat entry or cross-team coordination" }, problem: { zh: "流程不可追踪、数据不一致、库存/生产/项目状态不透明", en: "Untraceable workflows, inconsistent data or opaque inventory, production and project status" }, deliverables: [{ zh: "流程与权限方案", en: "Workflow and permission design" }, { zh: "原型与内部系统", en: "Prototype and internal system" }, { zh: "数据看板", en: "Operational dashboards" }], boundary: { zh: "数据迁移、清洗和第三方集成需单独评估。", en: "Data migration, cleanup and third-party integrations require separate assessment." } },
  { slug: "knowledge-assistants", title: { zh: "企业知识管理", en: "Business Knowledge Management" }, audience: { zh: "FAQ、产品资料、话术与制度复杂的团队", en: "Teams with complex FAQs, product materials, scripts and policies" }, problem: { zh: "找资料慢、答复不一致、培训成本高", en: "Slow retrieval, inconsistent answers and high training costs" }, deliverables: [{ zh: "知识结构与证据卡", en: "Knowledge structure and evidence cards" }, { zh: "知识库或问答助手原型", en: "Knowledge-base or assistant prototype" }, { zh: "转人工与质量规则", en: "Human handoff and quality rules" }], boundary: { zh: "模型、数据权限和上线方式依资料及风险评估决定。", en: "Model choice, data access and launch approach depend on materials and risk review." } },
  { slug: "sales-customer-management", title: { zh: "销售与客户管理", en: "Sales & Customer Management" }, audience: { zh: "需要统一客户信息、跟进节奏和销售协同的团队", en: "Teams that need clearer customer information, follow-up rhythm and sales coordination" }, problem: { zh: "客户信息分散、跟进记录不一致、交接容易遗漏", en: "Customer information is fragmented, follow-up records vary and handoffs are missed" }, deliverables: [{ zh: "客户信息与阶段结构", en: "Customer information and stage structure" }, { zh: "跟进流程与提醒规则", en: "Follow-up workflow and reminder rules" }, { zh: "销售协同看板原型", en: "Sales coordination dashboard prototype" }], boundary: { zh: "现有 CRM、数据迁移和权限规则需单独评估。", en: "Existing CRM, data migration and permission rules require separate assessment." } },
  { slug: "marketing-content", title: { zh: "内容与营销增长", en: "Content & Marketing Growth" }, audience: { zh: "需要长期内容、搜索和增长协同的品牌", en: "Brands that need content, search and growth work to operate together" }, problem: { zh: "内容断裂、官网与社媒不协同、搜索可见性弱", en: "Fragmented content, disconnected site and social work, weak search visibility" }, deliverables: [{ zh: "采购问题库", en: "Buyer-question library" }, { zh: "内容矩阵", en: "Content matrix" }, { zh: "官网/FAQ 改进与复盘", en: "Website/FAQ improvement and review" }], boundary: { zh: "不承诺排名、流量或增长数字；以内容与复测口径协商。", en: "No ranking, traffic or growth guarantee; content and review criteria are agreed by scope." } },
  { slug: "workflow-automation", title: { zh: "自动化与工作流", en: "Automation & Workflows" }, audience: { zh: "有重复性运营、内容或协作任务的团队", en: "Teams with repeated operations, content or coordination work" }, problem: { zh: "手工复制、重复录入、任务无法复盘", en: "Manual copying, repeated entry and work that cannot be reviewed" }, deliverables: [{ zh: "工作流地图", en: "Workflow map" }, { zh: "自动化方案", en: "Automation design" }, { zh: "岗位助手与质量检查", en: "Role assistants and quality checks" }], boundary: { zh: "自动化前需确认系统权限、异常处理和人工复核。", en: "Permissions, exception handling and human review must be confirmed before automation." } },
  { slug: "data-analytics-dashboards", title: { zh: "数据分析与经营看板", en: "Data Analytics & Operating Dashboards" }, audience: { zh: "需要统一经营口径、追踪数据和复盘节奏的团队", en: "Teams that need shared operating definitions, data tracking and review rhythm" }, problem: { zh: "数据分散、口径不一、管理者难以判断业务状态", en: "Data is fragmented, definitions vary and leaders cannot see business status clearly" }, deliverables: [{ zh: "指标与数据源清单", en: "Metric and data-source list" }, { zh: "经营看板原型", en: "Operating dashboard prototype" }, { zh: "复盘与人工核验规则", en: "Review and human-verification rules" }], boundary: { zh: "数据质量、权限、接口与历史清洗需先明确范围。", en: "Data quality, permissions, interfaces and historical cleanup need scoped confirmation." } },
];

export const businessGoals: BusinessGoal[] = services.map((service, index) => ({
  ...service,
  id: service.slug,
  summary: service.problem,
  customerProblems: [service.problem],
  outcomeDirections: service.deliverables,
  featured: index < 4,
  industrySlugs: [],
  scenarioSlugs: [],
}));

export const industries: Industry[] = [
  { slug: "professional-services", title: { zh: "专业服务与律师事务所", en: "Professional Services & Law Firms" }, summary: { zh: "适合梳理中英文官网、内容权限与客户信息入口。", en: "Suitable for structuring bilingual sites, content permissions and client-information entry points." }, scenarios: [{ zh: "中英文官网与服务内容结构", en: "Bilingual website and service structure" }, { zh: "资料权限与知识边界", en: "Material permissions and knowledge boundaries" }, { zh: "客户信息入口规划", en: "Client-information entry planning" }], risks: [{ zh: "客户资料、案件信息和权限需要纳入项目范围。", en: "Client materials, case information and permissions belong in the project scope." }], serviceSlugs: ["websites-portals", "knowledge-assistants", "sales-customer-management"] },
  { slug: "manufacturing-export", title: { zh: "制造业与外贸", en: "Manufacturing & Export" }, summary: { zh: "围绕资料、报价、库存、订单和生产协同组织可讨论的业务场景。", en: "Frames business scenarios around materials, quotes, inventory, orders and production coordination." }, scenarios: [{ zh: "产品资料与报价知识库", en: "Product and quotation knowledge base" }, { zh: "库存查询与订单协同", en: "Inventory lookup and order coordination" }, { zh: "外贸多语内容", en: "Export multilingual content" }], risks: [{ zh: "主数据、库存准确性及现有系统接口需要纳入范围。", en: "Master data, inventory accuracy and existing-system interfaces belong in scope." }], serviceSlugs: ["business-systems", "knowledge-assistants", "websites-portals"] },
  { slug: "retail-consumer", title: { zh: "零售与消费", en: "Retail & Consumer Brands" }, summary: { zh: "把品牌官网、内容运营、客服知识和产品教育放进同一业务路径。", en: "Connect the brand site, content operations, support knowledge and product education in one business path." }, scenarios: [{ zh: "品牌官网与产品教育", en: "Brand site and product education" }, { zh: "客服知识与内容运营", en: "Support knowledge and content operations" }, { zh: "采购问题与 FAQ", en: "Buyer questions and FAQs" }], risks: [{ zh: "功效、价格、评价与客户素材需要明确使用范围。", en: "Claims, prices, reviews and client assets need a clear usage scope." }], serviceSlugs: ["websites-portals", "marketing-content", "knowledge-assistants"] },
  { slug: "education", title: { zh: "教育与培训", en: "Education & Training" }, summary: { zh: "围绕课程资料、学习者沟通、内容维护与运营记录讨论适配方向。", en: "Discuss fit around course materials, learner communication, content maintenance and operating records." }, scenarios: [{ zh: "课程与招生信息门户", en: "Course and admissions information portal" }, { zh: "课程知识库", en: "Course knowledge base" }, { zh: "学习与运营数据看板", en: "Learning and operating dashboard" }], risks: [{ zh: "学习者隐私、课程版权与访问角色需要纳入范围。", en: "Learner privacy, course rights and access roles belong in scope." }], serviceSlugs: ["websites-portals", "knowledge-assistants", "data-analytics-dashboards"] },
  { slug: "healthcare", title: { zh: "医疗健康", en: "Healthcare" }, summary: { zh: "围绕公开健康教育、内部资料管理和流程记录讨论边界清晰的方向。", en: "Discuss bounded directions around public health education, internal material management and process records." }, scenarios: [{ zh: "健康教育门户", en: "Health education portal" }, { zh: "资料知识管理", en: "Material knowledge management" }, { zh: "表单与流程记录", en: "Form and workflow records" }], risks: [{ zh: "医疗建议、个人信息和监管要求需要专项确认。", en: "Medical advice, personal data and regulatory requirements need specific confirmation." }], serviceSlugs: ["websites-portals", "knowledge-assistants", "workflow-automation"] },
  { slug: "financial-services", title: { zh: "金融与金融服务", en: "Financial Services" }, summary: { zh: "围绕客户沟通、资料权限、流程记录和经营分析讨论可界定方向。", en: "Discuss bounded directions around client communication, material permissions, workflow records and operating analysis." }, scenarios: [{ zh: "客户管理与跟进", en: "Customer management and follow-up" }, { zh: "资料权限与知识管理", en: "Material permissions and knowledge management" }, { zh: "经营分析看板", en: "Operating analytics dashboard" }], risks: [{ zh: "合规、适当性、个人信息和留痕要求需要先明确。", en: "Compliance, suitability, personal-data and recordkeeping requirements must be clarified first." }], serviceSlugs: ["sales-customer-management", "knowledge-assistants", "data-analytics-dashboards"] },
  { slug: "agriculture-production", title: { zh: "农牧与生产管理", en: "Agriculture & Production Management" }, summary: { zh: "从录单、批次记录、巡检和经营看板等可界定流程梳理方向。", en: "Explore bounded workflows such as entry capture, batch records, inspections and operating dashboards." }, scenarios: [{ zh: "录单与批次/生产记录", en: "Entry capture and batch/production records" }, { zh: "巡检流程", en: "Inspection workflows" }, { zh: "经营数据看板", en: "Operating dashboards" }], risks: [{ zh: "现场网络、数据来源与人工复核责任需要写入范围。", en: "Field connectivity, data sources and human-review responsibility belong in scope." }], serviceSlugs: ["business-systems", "workflow-automation", "data-analytics-dashboards"] },
  { slug: "nonprofit-foundation", title: { zh: "公益组织与基金会", en: "Nonprofits & Foundations" }, summary: { zh: "围绕官网、项目透明度内容与项目协同设计可维护入口。", en: "Design maintainable entry points around websites, transparency content and project coordination." }, scenarios: [{ zh: "公益官网与项目展示", en: "Public-interest website and project presentation" }, { zh: "透明度内容与资料结构", en: "Transparency content and material structure" }, { zh: "志愿者或项目协同", en: "Volunteer or project coordination" }], risks: [{ zh: "受益人隐私、捐赠信息和公开范围应在范围中说明。", en: "Beneficiary privacy, donation information and publication scope should be stated in scope." }], serviceSlugs: ["websites-portals", "business-systems", "workflow-automation"] },
];

export const businessScenarios: BusinessScenario[] = [
  { id: "website-portal", slug: "website-portal", title: { zh: "企业官网与数字化门户", en: "Business Website & Digital Portal" }, summary: { zh: "把公开信息、服务路径与后续入口组织为清晰结构。", en: "Organize public information, service paths and future entry points into a clear structure." }, customerProblems: [{ zh: "官网信息分散、访问者难以判断下一步", en: "Website information is scattered and visitors cannot find the next step" }], deliverables: [{ zh: "信息架构与页面原型", en: "Information architecture and page prototype" }, { zh: "内容与权限清单", en: "Content and permission checklist" }], goalSlugs: ["websites-portals"], industrySlugs: ["professional-services", "retail-consumer", "education"], featured: true },
  { id: "crm-customer-management", slug: "crm-customer-management", title: { zh: "CRM 与客户管理", en: "CRM & Customer Management" }, summary: { zh: "梳理客户信息、跟进阶段与跨角色协同。", en: "Structure customer information, follow-up stages and cross-role coordination." }, customerProblems: [{ zh: "客户信息与跟进记录分散", en: "Customer information and follow-up records are fragmented" }], deliverables: [{ zh: "字段与阶段结构", en: "Field and stage structure" }, { zh: "跟进与交接规则原型", en: "Follow-up and handoff-rule prototype" }], goalSlugs: ["sales-customer-management"], industrySlugs: ["professional-services", "retail-consumer", "financial-services"], featured: true },
  { id: "inventory-order-lookup", slug: "inventory-order-lookup", title: { zh: "库存与订单查询", en: "Inventory & Order Lookup" }, summary: { zh: "围绕可追溯的数据来源、查询路径和人工核验讨论方案。", en: "Discuss an approach around traceable data sources, lookup paths and human verification." }, customerProblems: [{ zh: "库存、订单和产品资料难以快速查询", en: "Inventory, orders and product materials are hard to retrieve quickly" }], deliverables: [{ zh: "数据与权限清单", en: "Data and permission checklist" }, { zh: "查询流程原型", en: "Lookup-flow prototype" }], goalSlugs: ["business-systems", "data-analytics-dashboards"], industrySlugs: ["manufacturing-export", "agriculture-production"], featured: true },
  { id: "enterprise-knowledge-base", slug: "enterprise-knowledge-base", title: { zh: "企业知识库", en: "Business Knowledge Base" }, summary: { zh: "让资料、FAQ、证据和转人工规则更易检索与维护。", en: "Make materials, FAQs, evidence and handoff rules easier to retrieve and maintain." }, customerProblems: [{ zh: "团队找资料慢、回答口径不一致", en: "Teams retrieve materials slowly and answers vary" }], deliverables: [{ zh: "知识结构与证据卡", en: "Knowledge structure and evidence cards" }, { zh: "问答原型与质量规则", en: "Q&A prototype and quality rules" }], goalSlugs: ["knowledge-assistants"], industrySlugs: ["professional-services", "education", "healthcare"], featured: true },
  { id: "ocr-form-entry", slug: "ocr-form-entry", title: { zh: "OCR 与表单录入", en: "OCR & Form Entry" }, summary: { zh: "从可界定单据、人工校验和异常处理开始梳理流程。", en: "Start with bounded forms, human checking and exception handling." }, customerProblems: [{ zh: "纸单或现场录入难以追溯", en: "Paper forms or field entry are hard to trace" }], deliverables: [{ zh: "表单与流程地图", en: "Form and workflow map" }, { zh: "人工核验规则", en: "Human-verification rules" }], goalSlugs: ["business-systems", "workflow-automation"], industrySlugs: ["agriculture-production", "healthcare", "manufacturing-export"], featured: false },
  { id: "approval-workflow", slug: "approval-workflow", title: { zh: "审批流与流程自动化", en: "Approval Flows & Workflow Automation" }, summary: { zh: "梳理重复任务、例外处理和人工复核边界。", en: "Structure repeated tasks, exception handling and human-review boundaries." }, customerProblems: [{ zh: "审批与协同依赖反复转发和人工提醒", en: "Approvals and coordination depend on repeated forwarding and manual reminders" }], deliverables: [{ zh: "流程与异常清单", en: "Workflow and exception checklist" }, { zh: "自动化原型", en: "Automation prototype" }], goalSlugs: ["workflow-automation"], industrySlugs: ["manufacturing-export", "financial-services", "nonprofit-foundation"], featured: false },
  { id: "content-lead-operations", slug: "content-lead-operations", title: { zh: "内容与线索运营", en: "Content & Lead Operations" }, summary: { zh: "围绕真实采购问题协调官网、FAQ、内容与线索记录。", en: "Coordinate website, FAQ, content and lead records around real buyer questions." }, customerProblems: [{ zh: "内容、官网和线索信息彼此脱节", en: "Content, website and lead information are disconnected" }], deliverables: [{ zh: "问题库与内容矩阵", en: "Question library and content matrix" }, { zh: "页面与复盘清单", en: "Page and review checklist" }], goalSlugs: ["marketing-content", "sales-customer-management"], industrySlugs: ["retail-consumer", "professional-services", "education"], featured: false },
  { id: "operating-dashboard", slug: "operating-dashboard", title: { zh: "数据分析与经营看板", en: "Data Analytics & Operating Dashboard" }, summary: { zh: "统一指标与数据来源，形成可复盘的经营视图。", en: "Align metrics and data sources into a reviewable operating view." }, customerProblems: [{ zh: "数据口径不一致，管理者难以判断状态", en: "Data definitions vary and leaders cannot assess status clearly" }], deliverables: [{ zh: "指标与数据源清单", en: "Metric and data-source list" }, { zh: "看板结构原型", en: "Dashboard-structure prototype" }], goalSlugs: ["data-analytics-dashboards"], industrySlugs: ["manufacturing-export", "financial-services", "agriculture-production"], featured: false },
];

export const serviceEnrichment: Record<string, ServiceEnrichment> = {
  "websites-portals": { summary: { zh: "把公开信息、咨询路径与后续数字化入口组织成可维护的第一印象。", en: "Organize public information, inquiry paths and future digital entry points into a maintainable first impression." }, commonProblems: [{ zh: "服务价值难以快速理解", en: "Service value is hard to understand quickly" }, { zh: "咨询入口与内容路径断裂", en: "Inquiry entry and content paths are disconnected" }], process: [{ zh: "内容与用户问题盘点", en: "Content and user-question inventory" }, { zh: "信息架构与原型确认", en: "Information architecture and prototype confirmation" }, { zh: "静态实现与质量检查", en: "Static implementation and quality checks" }], industrySlugs: ["professional-services", "retail-consumer", "nonprofit-foundation"] },
  "business-systems": { summary: { zh: "从流程、角色和数据边界出发，建设可追踪的内部业务工具。", en: "Build traceable internal tools from workflows, roles and data boundaries." }, commonProblems: [{ zh: "表格与人工转发造成重复录入", en: "Spreadsheets and forwarding cause repeated entry" }, { zh: "管理者看不到库存、生产或项目状态", en: "Leaders cannot see inventory, production or project status" }], process: [{ zh: "流程与数据源评估", en: "Workflow and data-source assessment" }, { zh: "权限与原型确认", en: "Permission and prototype confirmation" }, { zh: "开发、测试与交接", en: "Development, testing and handoff" }], industrySlugs: ["manufacturing-export", "agriculture-production", "nonprofit-foundation"] },
  "knowledge-assistants": { summary: { zh: "把资料、证据、问答和转人工规则变成可控的知识服务。", en: "Turn materials, evidence, answers and handoff rules into a controlled knowledge service." }, commonProblems: [{ zh: "资料很多但找不到可信答案", en: "There are many materials but no reliable answers" }, { zh: "客服销售口径和证据不一致", en: "Support and sales messages and evidence are inconsistent" }], process: [{ zh: "资料与权限盘点", en: "Material and access inventory" }, { zh: "知识结构与边界设计", en: "Knowledge structure and boundary design" }, { zh: "原型、回归问题与人工复核", en: "Prototype, regression questions and human review" }], industrySlugs: ["professional-services", "manufacturing-export", "retail-consumer"] },
  "sales-customer-management": { summary: { zh: "围绕客户信息、跟进阶段和协同动作建立可讨论的管理结构。", en: "Create a discussable management structure around customer information, follow-up stages and team actions." }, commonProblems: [{ zh: "客户信息分散在表格、聊天和个人记录中", en: "Customer information is spread across spreadsheets, chats and personal notes" }, { zh: "跟进节奏与交接规则不一致", en: "Follow-up rhythm and handoff rules are inconsistent" }], process: [{ zh: "客户旅程与字段梳理", en: "Customer-journey and field mapping" }, { zh: "阶段、权限与提醒原型", en: "Stage, permission and reminder prototype" }, { zh: "测试记录与复盘规则", en: "Testing records and review rules" }], industrySlugs: ["professional-services", "retail-consumer", "financial-services"] },
  "workflow-automation": { summary: { zh: "选择可复盘的重复动作，设计有人工兜底的自动化。", en: "Select reviewable repeated work and design automation with human fallback." }, commonProblems: [{ zh: "跨工具复制和重复录入", en: "Copying and repeated entry across tools" }, { zh: "流程异常缺少明确责任", en: "Workflow exceptions lack a clear responsible role" }], process: [{ zh: "任务与异常梳理", en: "Task and exception mapping" }, { zh: "自动化与人工复核设计", en: "Automation and human-review design" }, { zh: "受控试点与复盘", en: "Controlled pilot and review" }], industrySlugs: ["manufacturing-export", "agriculture-production", "retail-consumer"] },
  "data-analytics-dashboards": { summary: { zh: "先统一指标、数据来源和复盘节奏，再讨论看板与分析方式。", en: "Align metrics, data sources and review rhythm before discussing dashboards and analysis." }, commonProblems: [{ zh: "经营数据口径不一致", en: "Operating data definitions are inconsistent" }, { zh: "团队难以从数据判断下一步", en: "Teams struggle to decide next actions from data" }], process: [{ zh: "指标与数据源盘点", en: "Metric and data-source inventory" }, { zh: "看板结构与核验规则", en: "Dashboard structure and verification rules" }, { zh: "复盘节奏与迭代", en: "Review rhythm and iteration" }], industrySlugs: ["manufacturing-export", "financial-services", "agriculture-production"] },
  "marketing-content": { summary: { zh: "让官网、FAQ、内容与搜索可见性围绕同一批真实采购问题协同。", en: "Align website, FAQ, content and search visibility around the same real buyer questions." }, commonProblems: [{ zh: "内容产出和官网信息脱节", en: "Content production and website information are disconnected" }, { zh: "没有可复测的 SEO/GEO 内容基线", en: "There is no repeatable SEO/GEO content baseline" }], process: [{ zh: "问题库与现有内容盘点", en: "Question library and existing-content inventory" }, { zh: "内容矩阵与页面优先级", en: "Content matrix and page priorities" }, { zh: "发布节奏与复测", en: "Publishing rhythm and repeat review" }], industrySlugs: ["retail-consumer", "manufacturing-export", "nonprofit-foundation"] },
  "diagnosis-consulting": { summary: { zh: "在投入开发前先确认优先级、范围、风险与验收方式。", en: "Confirm priorities, scope, risks and acceptance before committing to development." }, commonProblems: [{ zh: "团队不确定第一步做什么", en: "The team is unsure what to do first" }, { zh: "需求、预算与验收没有共同边界", en: "Requirements, budget and acceptance lack shared boundaries" }], process: [{ zh: "初步沟通", en: "Initial conversation" }, { zh: "业务诊断与范围草案", en: "Business diagnosis and scope draft" }, { zh: "试点或后续实施建议", en: "Pilot or next-stage implementation recommendation" }], industrySlugs: ["professional-services", "manufacturing-export", "retail-consumer", "agriculture-production", "nonprofit-foundation"] },
};

export const industryEnrichment: Record<string, IndustryEnrichment> = {
  "professional-services": { background: { zh: "专业服务需要在公开表达、客户咨询、资料权限与保密边界之间取得平衡。", en: "Professional services must balance public communication, client inquiry, material permissions and confidentiality." }, commonProblems: [{ zh: "中英文服务信息难以一致维护", en: "Bilingual service information is hard to maintain consistently" }, { zh: "客户资料与公开内容边界不清", en: "Client-material and public-content boundaries are unclear" }], requiredMaterials: [{ zh: "已确认服务内容与可公开资料", en: "Confirmed service content and public materials" }, { zh: "角色、权限与保密要求", en: "Roles, permissions and confidentiality requirements" }], caseSlugs: ["law-firm-bilingual-site"] },
  "manufacturing-export": { background: { zh: "制造与外贸场景通常同时涉及产品资料、报价、订单、库存和多语沟通。", en: "Manufacturing and export often combine product materials, quotes, orders, inventory and multilingual communication." }, commonProblems: [{ zh: "库存与订单信息分散", en: "Inventory and order information is fragmented" }, { zh: "产品资料和报价难以快速检索", en: "Product materials and quotations are hard to retrieve quickly" }], requiredMaterials: [{ zh: "产品、库存和订单数据样本", en: "Product, inventory and order data samples" }, { zh: "现有系统与接口说明", en: "Existing-system and interface notes" }], caseSlugs: ["furniture-inventory-lookup"] },
  "retail-consumer": { background: { zh: "零售与消费品牌需要把产品教育、内容、客服与公开渠道连成可维护的路径。", en: "Retail and consumer brands need maintainable paths across product education, content, support and public channels." }, commonProblems: [{ zh: "产品教育与内容口径不一致", en: "Product education and content messages are inconsistent" }, { zh: "官网、社媒与客服不能协同", en: "Website, social and support cannot work together" }], requiredMaterials: [{ zh: "产品事实、FAQ 与内容资产", en: "Product facts, FAQs and content assets" }, { zh: "可公开素材及其授权", en: "Public assets and their permissions" }], caseSlugs: [] },
  "education": { background: { zh: "教育与培训团队可先从课程资料、学习者问题和公开信息结构梳理起。", en: "Education and training teams can start by structuring course materials, learner questions and public information." }, commonProblems: [{ zh: "课程资料分散且难以维护", en: "Course materials are scattered and hard to maintain" }, { zh: "学习者问题缺少一致入口", en: "Learner questions lack a consistent entry point" }], requiredMaterials: [{ zh: "可公开课程与招生资料", en: "Public course and admissions materials" }, { zh: "学习者角色与隐私边界", en: "Learner roles and privacy boundaries" }], caseSlugs: [] },
  "healthcare": { background: { zh: "医疗健康内容与流程需先明确公开边界、人工复核与资料权限。", en: "Healthcare content and workflows need clear public boundaries, human review and material permissions first." }, commonProblems: [{ zh: "健康教育资料难以统一维护", en: "Health-education materials are hard to maintain consistently" }, { zh: "表单与流程记录不易追溯", en: "Forms and workflow records are hard to trace" }], requiredMaterials: [{ zh: "可公开教育资料", en: "Public education materials" }, { zh: "角色、权限与专项要求", en: "Roles, permissions and specific requirements" }], caseSlugs: [] },
  "financial-services": { background: { zh: "金融服务应在客户沟通、资料权限和记录要求明确后讨论系统与分析方向。", en: "Financial services should clarify client communication, material permissions and recordkeeping before discussing systems and analytics." }, commonProblems: [{ zh: "客户跟进和资料权限分散", en: "Customer follow-up and material permissions are fragmented" }, { zh: "经营数据难以形成共同口径", en: "Operating data lacks shared definitions" }], requiredMaterials: [{ zh: "可使用的字段与资料范围", en: "Permitted fields and material scope" }, { zh: "合规与留痕要求", en: "Compliance and recordkeeping requirements" }], caseSlugs: [] },
  "agriculture-production": { background: { zh: "农牧与生产管理从录单、批次、巡检和数据复盘等可界定环节开始更稳妥。", en: "Agriculture and production management are safer to start with bounded entry, batch, inspection and review steps." }, commonProblems: [{ zh: "纸单或现场录入难以追溯", en: "Paper or field entry is hard to trace" }, { zh: "生产记录和经营复盘脱节", en: "Production records and operating review are disconnected" }], requiredMaterials: [{ zh: "现场流程和代表性单据", en: "Field workflows and representative forms" }, { zh: "数据来源与人工复核责任", en: "Data sources and human-review responsibility" }], caseSlugs: ["agriculture-ocr-production"] },
  "nonprofit-foundation": { background: { zh: "公益组织需要在项目透明度、公众沟通和受益人隐私之间建立可维护边界。", en: "Nonprofits need maintainable boundaries between project transparency, public communication and beneficiary privacy." }, commonProblems: [{ zh: "项目内容更新与公开范围不清", en: "Project updates and publication boundaries are unclear" }, { zh: "公开透明与隐私保护难兼顾", en: "Transparency and privacy are hard to balance" }], requiredMaterials: [{ zh: "项目资料与可公开范围", en: "Project materials and publication boundaries" }, { zh: "隐私、捐赠与角色规则", en: "Privacy, donation and role rules" }], caseSlugs: ["nonprofit-foundation-site"] },
};

export const cases: CaseStudy[] = [
  { slug: "law-firm-bilingual-site", title: { zh: "专业服务双语官网", en: "Professional Services Bilingual Website" }, status: "concept", background: { zh: "典型业务场景，概念方案，非客户实绩。", en: "Typical business scenario. Concept proposal, not client work." }, problem: { zh: "中英文服务信息、内容维护与权限边界需要系统梳理。", en: "Bilingual service information, content maintenance and permission boundaries need structure." }, objective: { zh: "形成清晰的信息架构与内容路径。", en: "Shape clear information architecture and content paths." }, implementation: [{ zh: "梳理内容与使用者问题", en: "Map content and user questions" }, { zh: "规划双语页面与管理边界", en: "Plan bilingual pages and administration boundaries" }], deliverables: [{ zh: "信息架构", en: "Information architecture" }, { zh: "权限清单", en: "Permission checklist" }, { zh: "可测试原型", en: "Testable prototype" }], result: { zh: "用于说明可讨论的交付结构。", en: "Illustrates a discussable delivery structure." }, nextStep: { zh: "了解交付方式", en: "Explore the delivery approach." }, confidentiality: { zh: "概念方案不涉及客户、案件或业务数据。", en: "This concept does not use client, case or business data." }, serviceSlugs: ["websites-portals", "business-systems"] },
  { slug: "nonprofit-foundation-site", title: { zh: "公益组织信息官网", en: "Nonprofit Information Website" }, status: "concept", background: { zh: "典型业务场景，概念方案，非客户实绩。", en: "Typical business scenario. Concept proposal, not client work." }, problem: { zh: "项目透明度内容、隐私和公众信息结构需要平衡。", en: "Project-transparency content, privacy and public information need balance." }, objective: { zh: "形成可维护的公开信息结构。", en: "Create a maintainable public-information structure." }, implementation: [{ zh: "梳理公开内容与隐私边界", en: "Map public-content and privacy boundaries" }], deliverables: [{ zh: "信息架构", en: "Information architecture" }, { zh: "内容清单", en: "Content checklist" }, { zh: "验收清单", en: "Acceptance checklist" }], result: { zh: "用于说明可讨论的交付结构。", en: "Illustrates a discussable delivery structure." }, nextStep: { zh: "了解交付方式", en: "Explore the delivery approach." }, confidentiality: { zh: "概念方案不涉及受益人或捐赠数据。", en: "This concept does not use beneficiary or donation data." }, serviceSlugs: ["websites-portals"] },
  { slug: "furniture-inventory-lookup", title: { zh: "外贸库存查询", en: "Export Inventory Lookup" }, status: "concept", background: { zh: "典型业务场景，概念方案，非客户实绩。", en: "Typical business scenario. Concept proposal, not client work." }, problem: { zh: "产品资料、库存与对外查询口径可能分散。", en: "Product materials, inventory and external lookup rules can be fragmented." }, objective: { zh: "梳理查询所需的数据、权限与流程。", en: "Map the data, permissions and flow needed for lookup." }, implementation: [{ zh: "梳理资料与数据来源", en: "Map materials and data sources" }], deliverables: [{ zh: "流程图", en: "Workflow map" }, { zh: "权限清单", en: "Permission checklist" }, { zh: "可测试原型", en: "Testable prototype" }], result: { zh: "用于说明可讨论的交付结构。", en: "Illustrates a discussable delivery structure." }, nextStep: { zh: "了解交付方式", en: "Explore the delivery approach." }, confidentiality: { zh: "概念方案不涉及库存、订单或客户数据。", en: "This concept does not use inventory, order or client data." }, serviceSlugs: ["business-systems", "knowledge-assistants"] },
  { slug: "agriculture-ocr-production", title: { zh: "农牧录单与生产管理", en: "Agriculture Entry & Production Management" }, status: "concept", background: { zh: "典型业务场景，概念方案，非客户实绩。", en: "Typical business scenario. Concept proposal, not client work." }, problem: { zh: "纸单或现场录入、生产记录和复盘可能存在断点。", en: "Paper or field entry, production records and review can have gaps." }, objective: { zh: "梳理录单与生产记录的业务流程。", en: "Map the business flow for entry capture and production records." }, implementation: [{ zh: "梳理现场流程与人工复核", en: "Map field workflow and human review" }], deliverables: [{ zh: "流程图", en: "Workflow map" }, { zh: "部署说明", en: "Deployment notes" }, { zh: "验收清单", en: "Acceptance checklist" }], result: { zh: "用于说明可讨论的交付结构。", en: "Illustrates a discussable delivery structure." }, nextStep: { zh: "了解交付方式", en: "Explore the delivery approach." }, confidentiality: { zh: "概念方案不涉及生产、经营或个人数据。", en: "This concept does not use production, operating or personal data." }, serviceSlugs: ["business-systems", "workflow-automation"] },
];

export const deliverySteps: DeliveryStep[] = [
  { number: "01", title: { zh: "初步沟通", en: "Initial Conversation" }, clientInput: { zh: "目标、现状与约束", en: "Goals, current state and constraints" }, responsibility: { zh: "判断适配性与下一步", en: "Assess fit and next step" }, output: { zh: "问题清单", en: "Question list" }, acceptance: { zh: "双方确认问题定义", en: "Shared problem definition" }, risk: { zh: "不构成报价或上线承诺", en: "Not a quote or launch commitment" } },
  { number: "02", title: { zh: "业务诊断", en: "Business Diagnosis" }, clientInput: { zh: "流程、资料、角色", en: "Workflows, materials and roles" }, responsibility: { zh: "梳理痛点与机会", en: "Map pain points and opportunities" }, output: { zh: "优先级地图", en: "Priority map" }, acceptance: { zh: "客户确认优先级", en: "Client confirms priorities" }, risk: { zh: "资料质量影响判断", en: "Material quality affects findings" } },
  { number: "03", title: { zh: "范围确认", en: "Scope Confirmation" }, clientInput: { zh: "预算、时限、责任", en: "Budget, timing and roles" }, responsibility: { zh: "定义范围、非范围与验收", en: "Define scope, exclusions and acceptance" }, output: { zh: "范围说明与验收清单", en: "Scope statement and acceptance checklist" }, acceptance: { zh: "范围共同确认", en: "Shared scope confirmation" }, risk: { zh: "变更影响周期和费用", en: "Changes affect timeline and fees" } },
  { number: "04", title: { zh: "原型或 Demo", en: "Prototype or Demo" }, clientInput: { zh: "代表资料与反馈", en: "Representative materials and feedback" }, responsibility: { zh: "建立可评审原型", en: "Build a reviewable prototype" }, output: { zh: "页面/流程/界面 Demo", en: "Page/workflow/interface demo" }, acceptance: { zh: "场景与边界确认", en: "Scenario and boundary confirmation" }, risk: { zh: "Demo 不等于上线", en: "A demo is not a launch" } },
  { number: "05", title: { zh: "开发与测试", en: "Development & Testing" }, clientInput: { zh: "内容、测试人、规则", en: "Content, testers and rules" }, responsibility: { zh: "实施、测试、修正", en: "Implement, test and refine" }, output: { zh: "版本与测试记录", en: "Version and test record" }, acceptance: { zh: "约定测试通过", en: "Agreed tests pass" }, risk: { zh: "第三方/模型费用另计", en: "Third-party/model fees are separate" } },
  { number: "06", title: { zh: "上线与培训", en: "Launch & Training" }, clientInput: { zh: "上线窗口与使用人员", en: "Launch window and users" }, responsibility: { zh: "受控发布、培训、交接", en: "Controlled release, training and handoff" }, output: { zh: "上线记录与培训材料", en: "Launch record and training materials" }, acceptance: { zh: "用户侧检查", en: "User-side check" }, risk: { zh: "部署方式依项目范围协商", en: "Deployment approach is agreed by project scope" } },
  { number: "07", title: { zh: "验收与维护", en: "Acceptance & Maintenance" }, clientInput: { zh: "验收人与反馈", en: "Acceptance representative and feedback" }, responsibility: { zh: "复盘、修复与维护交接", en: "Review, fix and maintenance handoff" }, output: { zh: "验收记录与维护边界", en: "Acceptance record and maintenance boundary" }, acceptance: { zh: "签收或待办清单", en: "Signoff or open-items list" }, risk: { zh: "维护以交付文件为准；迁移清洗另评估", en: "Maintenance follows delivery documents; migration/cleanup is separately assessed" } },
];

export const faqs: FAQItem[] = [
  ["fit", "范围", "什么团队适合开始？", "适合有明确业务问题、愿意提供代表性资料并共同验证的团队；可先从范围可控的场景开始。", "Which teams are a fit?", "Teams with a defined business problem, representative materials and a shared validation path; begin with a bounded scenario."],
  ["materials", "流程", "需要准备什么资料？", "通常需要目标、现有流程、代表性资料、角色和约束；实际清单随项目范围确认。", "What materials are needed?", "Typically goals, current workflows, representative materials, roles and constraints; the final list follows scope."],
  ["timeline", "周期报价", "周期如何评估？", "按范围、资料质量、接口、测试和上线条件评估；不会在未确认范围前给出固定承诺。", "How is timing assessed?", "By scope, material quality, integrations, testing and launch conditions; no fixed commitment precedes confirmation."],
  ["pricing", "周期报价", "报价如何形成？", "按确认的交付范围、风险、协作与维护边界协商，不展示不成熟价格。", "How is pricing formed?", "It is discussed from confirmed deliverables, risk, collaboration and maintenance boundaries; immature pricing is not displayed."],
  ["portal", "范围", "网站和数字化门户有什么区别？", "网站主要面向公开信息与咨询；门户可能涉及受邀访问、项目资料或业务入口，权限和数据边界需要单独确认。", "How does a portal differ from a website?", "A site is mainly public information and inquiry; a portal may involve invited access, project materials or business entry points and needs separate permission/data definition."],
  ["saas", "范围", "定制系统和 SaaS 怎么选？", "先看流程差异、数据/权限、现有工具和维护能力；标准需求可先评估 SaaS，关键差异再考虑定制。", "Custom system or SaaS?", "Start with workflow differences, data/permissions, existing tools and maintenance capacity; evaluate SaaS for standard needs before custom work for critical differences."],
  ["knowledge", "模型与数据", "知识库和网盘有什么区别？", "网盘保存文件；知识库需要定义结构、来源、权限、更新和可检索的问答边界。", "Knowledge base vs. drive?", "A drive stores files; a knowledge base defines structure, sources, permissions, updates and retrieval/answer boundaries."],
  ["model", "模型与数据", "需要训练自己的大模型吗？", "不默认需要。先判断资料、任务、权限、模型能力和评测要求，再决定是否需要额外训练或其他方案。", "Do we need to train a model?", "Not by default. Review materials, tasks, permissions, model capability and evaluation needs before deciding on training or alternatives."],
  ["security", "模型与数据", "数据、权限和保密如何处理？", "先定义数据来源、可访问角色、保留方式、第三方与人工复核；高风险资料需要专项确认。", "How are data, access and confidentiality handled?", "Define sources, access roles, retention, third parties and human review first; high-risk materials need specific confirmation."],
  ["inventory", "流程", "库存或生产系统如何接入？", "先核验主数据、现有系统、接口、更新频率和人工纠错流程；迁移和清洗另行评估。", "How can inventory or production systems connect?", "Verify master data, existing systems, interfaces, update frequency and correction flow first; migration/cleanup are separately assessed."],
  ["support", "模型与数据", "AI 客服需要哪些资料？", "需要已确认的 FAQ、产品事实、证据来源、禁说项、转人工规则和回归问题。", "What does AI support need?", "Confirmed FAQs, product facts, evidence sources, do-not-say rules, human handoff and regression questions."],
  ["seo", "范围", "官网 SEO/GEO 如何衡量？", "从可索引页面、真实采购问题、内容质量、技术可访问性和持续复测建立基线；不保证排名或流量。", "How is SEO/GEO measured?", "Build a baseline from indexable pages, real buyer questions, content quality, technical access and repeat review; no rank or traffic guarantee."],
].map(([id, categoryZh, questionZh, answerZh, questionEn, answerEn]) => ({ id, category: { zh: categoryZh, en: categoryZh }, question: { zh: questionZh, en: questionEn }, answer: { zh: answerZh, en: answerEn } }));

export const statusLabels: Record<CaseStatus, LocalizedText> = {
  live: { zh: "已上线", en: "Live" }, "in-development": { zh: "开发中", en: "In development" }, pilot: { zh: "试点", en: "Pilot" }, demo: { zh: "演示", en: "Demo" }, concept: { zh: "概念", en: "Concept" },
};
