import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { CardList, FaqList } from "@/components/content-sections";
import { businessScenarios, industries, services, text } from "@/lib/content-data";
import { isChineseSite } from "@/lib/site-data";
import { buildPageMetadata, pageBreadcrumbJsonLd } from "@/lib/seo-data";
import { JsonLd } from "@/components/json-ld";

export const metadata: Metadata = buildPageMetadata({ path: "/solutions", title: isChineseSite ? "按业务目标找解决方案" : "Solutions by Business Goal", description: isChineseSite ? "按客户希望改善的业务目标浏览七类方向。" : "Browse seven directions by the business goal a team wants to improve." });

export default function SolutionsPage() { const locale = isChineseSite ? "zh" as const : "en" as const; return <main><JsonLd data={pageBreadcrumbJsonLd(isChineseSite ? "按业务目标" : "Business Goals", "/solutions")} /><section className="home-hero text-white"><div className="section-wrap py-16 md:py-20"><p className="kicker kicker-gold">{isChineseSite ? "按业务目标" : "BUSINESS GOALS"}</p><h1 className="mt-5 max-w-4xl text-balance text-4xl font-black leading-tight md:text-6xl">{isChineseSite ? "按希望改善的业务目标，找到可讨论的方向。" : "Find a discussable direction by the business goal you want to improve."}</h1><p className="mt-6 max-w-3xl text-lg leading-9 text-slate-300">{isChineseSite ? "七类方向覆盖官网、系统、知识、客户管理、内容、自动化与经营分析；范围以资料和确认后的边界为准。" : "Seven directions cover websites, systems, knowledge, customer management, content, automation and operating analysis; scope follows materials and confirmed boundaries."}</p></div></section><section className="section-wrap py-16"><CardList locale={locale} items={services.map((service) => ({ title: service.title, body: service.problem, href: `/solutions/${service.slug}` }))} /></section><section className="light-band py-16"><div className="section-wrap grid gap-8 md:grid-cols-2"><div><h2 className="text-3xl font-black text-navy-950">{isChineseSite ? "也可按行业查找" : "Also browse by industry"}</h2><div className="mt-6 grid gap-3">{industries.slice(0, 4).map((industry) => <Link href={`/industries/${industry.slug}`} key={industry.slug} className="surface rounded-lg p-4"><h3 className="font-black text-navy-950">{text(industry.title, locale)}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text(industry.summary, locale)}</p></Link>)}</div><Link href="/industries" className="mt-6 inline-block text-sm font-black text-vector-blue">{isChineseSite ? "查看全部行业" : "View all industries"}</Link></div><div><h2 className="text-3xl font-black text-navy-950">{isChineseSite ? "或按典型场景查找" : "Or browse by scenario"}</h2><div className="mt-6 grid gap-3">{businessScenarios.slice(0, 4).map((scenario) => <Link href="/scenarios" key={scenario.slug} className="surface rounded-lg p-4"><h3 className="font-black text-navy-950">{text(scenario.title, locale)}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text(scenario.summary, locale)}</p></Link>)}</div><Link href="/scenarios" className="mt-6 inline-block text-sm font-black text-vector-blue">{isChineseSite ? "查看全部典型场景" : "View all scenarios"}</Link></div></div></section><section className="section-wrap py-16"><h2 className="text-3xl font-black text-navy-950">FAQ</h2><div className="mt-7"><FaqList locale={locale} limit={4} /></div><Link href="/delivery-process" className="button-secondary mt-8">{isChineseSite ? "不知道从哪里开始？查看交付方式" : "Not sure where to start? Explore delivery"}<ArrowRight size={16} /></Link></section></main>; }
