import type { Metadata } from "next";
import { JsonLd } from "@/components/json-ld";
import { isChineseSite } from "@/lib/site-data";
import { buildPageMetadata, pageBreadcrumbJsonLd } from "@/lib/seo-data";

const chineseTopics = ["制造流程如何从表格、纸单到可追踪系统", "企业知识库与网盘有什么区别", "律所网站、客户资料与权限：保密边界怎么做", "库存查询系统要先梳理哪些数据与流程", "企业需要训练自己的大模型吗", "AI 客服上线前需要准备哪些资料", "官网 SEO/GEO：如何把真实采购问题写成可发现内容", "定制系统和 SaaS 怎么选", "AI 营销与内容运营如何连接官网、FAQ 和复盘", "农牧录单与生产管理：哪些流程适合先做数字化", "公益组织官网如何展示项目透明度且保护隐私", "多模型 API 接入前的权限、成本与支持检查表"];
const englishTopics = ["Moving manufacturing workflows from spreadsheets and paper to traceable systems", "Knowledge bases and shared drives: what is the difference?", "Law-firm websites, client materials and permissions: defining confidentiality boundaries", "What data and workflows should be mapped before building an inventory lookup system?", "Does a business need to train its own large language model?", "What materials are needed before launching AI customer support?", "Website SEO/GEO: turning real buyer questions into discoverable content", "Custom systems or SaaS: how should a team choose?", "Connecting AI marketing and content operations to a website, FAQ and review cycle", "Livestock and agriculture: which entry and production workflows should digitise first?", "How can nonprofit websites show project transparency while protecting privacy?", "A permissions, cost and support checklist before multi-model API access"];
export const metadata: Metadata = buildPageMetadata({ path: "/insights", title: isChineseSite ? "洞察与采购问题" : "Insights & Buyer Questions", description: isChineseSite ? "围绕企业 AI 与数字化系统采购问题的内容方向。" : "Content directions around business AI and digital-system buying questions." });
export default function InsightsPage() {
  const topics = isChineseSite ? chineseTopics : englishTopics;

  return <main><JsonLd data={pageBreadcrumbJsonLd(isChineseSite ? "洞察" : "Insights", "/insights")} /><section className="light-band border-b border-slate-200 py-16"><div className="section-wrap max-w-4xl"><p className="kicker">{isChineseSite ? "洞察" : "INSIGHTS"}</p><h1 className="mt-5 text-4xl font-black text-navy-950 md:text-6xl">{isChineseSite ? "从真实采购问题出发的内容方向。" : "Content directions built from real buying questions."}</h1><p className="mt-6 text-lg leading-9 text-slate-600">{isChineseSite ? "以下主题用于帮助团队梳理问题、资料与范围。" : "These topics help teams structure problems, materials and scope."}</p></div></section><section className="section-wrap py-16"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{topics.map((topic, index) => <article key={topic} className="surface rounded-lg p-6"><p className="text-sm font-black text-vector-blue">{String(index + 1).padStart(2, "0")}</p><h2 className="mt-4 text-lg font-black leading-7 text-navy-950">{topic}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{isChineseSite ? "围绕业务问题、资料结构与实施边界展开。" : "Explore the business problem, material structure and implementation boundaries."}</p></article>)}</div></section></main>;
}
