import type { Metadata } from "next";
import Link from "next/link";
import { JsonLd } from "@/components/json-ld";
import { businessScenarios, industries, services, text } from "@/lib/content-data";
import { isChineseSite } from "@/lib/site-data";
import { buildPageMetadata, pageBreadcrumbJsonLd } from "@/lib/seo-data";

export const metadata: Metadata = buildPageMetadata({ path: "/scenarios", title: isChineseSite ? "典型业务场景" : "Typical Business Scenarios", description: isChineseSite ? "按可讨论的客户问题、交付成果与适用方向浏览典型场景。" : "Browse typical scenarios through discussable customer problems, deliverables and fit." });

export default function ScenariosPage() {
  const locale = isChineseSite ? "zh" as const : "en" as const;
  return <main><JsonLd data={pageBreadcrumbJsonLd(isChineseSite ? "典型业务场景" : "Typical Business Scenarios", "/scenarios")} /><section className="light-band border-b border-slate-200 py-16 md:py-20"><div className="section-wrap max-w-4xl"><p className="kicker">{isChineseSite ? "典型场景" : "SCENARIOS"}</p><h1 className="mt-5 text-balance text-4xl font-black text-navy-950 md:text-6xl">{isChineseSite ? "从可讨论的业务场景找到路径。" : "Find a path through a discussable business scenario."}</h1><p className="mt-6 text-lg leading-9 text-slate-600">{isChineseSite ? "这些是分类入口，不是客户项目或项目经验；每项说明问题、可交付成果和相关方向。" : "These are classification entries, not client projects or project experience. Each explains a problem, possible deliverables and related directions."}</p></div></section><section className="section-wrap py-16"><div className="grid gap-5 md:grid-cols-2">{businessScenarios.map((scenario) => { const goals = services.filter((item) => scenario.goalSlugs.includes(item.slug)); const relatedIndustries = industries.filter((item) => scenario.industrySlugs.includes(item.slug)); return <article key={scenario.slug} className="surface rounded-lg p-6"><h2 className="text-xl font-black text-navy-950">{text(scenario.title, locale)}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{text(scenario.summary, locale)}</p><p className="mt-5 text-xs font-black uppercase tracking-wider text-vector-blue">{locale === "zh" ? "客户问题" : "Customer problem"}</p><p className="mt-1 text-sm leading-6 text-slate-700">{text(scenario.customerProblems[0], locale)}</p><p className="mt-5 text-xs font-black uppercase tracking-wider text-vector-blue">{locale === "zh" ? "可交付成果" : "Example deliverables"}</p><ul className="mt-2 text-sm leading-6 text-slate-700">{scenario.deliverables.map((item) => <li key={text(item, locale)}>• {text(item, locale)}</li>)}</ul><div className="mt-5 flex flex-wrap gap-2">{goals.map((item) => <Link key={item.slug} href={`/solutions/${item.slug}`} className="rounded-full border border-blue-100 px-3 py-1 text-xs font-black text-vector-blue">{text(item.title, locale)}</Link>)}{relatedIndustries.map((item) => <Link key={item.slug} href={`/industries/${item.slug}`} className="rounded-full border border-slate-200 px-3 py-1 text-xs font-black text-slate-700">{text(item.title, locale)}</Link>)}</div></article>; })}</div></section></main>;
}
