import type { Metadata } from "next";
import Link from "next/link";
import { CardList } from "@/components/content-sections";
import { JsonLd } from "@/components/json-ld";
import { businessScenarios, industries, services, text } from "@/lib/content-data";
import { isChineseSite } from "@/lib/site-data";
import { buildPageMetadata, pageBreadcrumbJsonLd } from "@/lib/seo-data";

export const metadata: Metadata = buildPageMetadata({ path: "/industries", title: isChineseSite ? "按行业找适配方向" : "Solutions by Industry", description: isChineseSite ? "按行业中的典型问题、可讨论场景与适配方向浏览。" : "Browse typical problems, discussable scenarios and relevant directions by industry." });
export default function IndustriesPage() { const locale = isChineseSite ? "zh" as const : "en" as const; return <main><JsonLd data={pageBreadcrumbJsonLd(isChineseSite ? "按行业" : "Industries", "/industries")} /><section className="light-band border-b border-slate-200 py-16 md:py-20"><div className="section-wrap max-w-4xl"><p className="kicker">{isChineseSite ? "按行业" : "INDUSTRIES"}</p><h1 className="mt-5 text-4xl font-black text-navy-950 md:text-6xl">{isChineseSite ? "从行业中的典型问题理解适配方向。" : "Understand relevant directions through typical industry problems."}</h1><p className="mt-6 text-lg leading-9 text-slate-600">{isChineseSite ? "行业不是唯一主干；也可以按业务目标或典型场景找到路径。" : "Industry is not the only path; browse by business goal or typical scenario as well."}</p></div></section><section className="section-wrap py-16"><CardList locale={locale} items={industries.map((item) => ({ title: item.title, body: item.summary, href: `/industries/${item.slug}` }))} /></section><section className="light-band py-16"><div className="section-wrap grid gap-8 md:grid-cols-2"><div><h2 className="text-2xl font-black text-navy-950">{isChineseSite ? "按业务目标" : "By business goal"}</h2><div className="mt-5 flex flex-wrap gap-2">{services.map((item) => <Link href={`/solutions/${item.slug}`} key={item.slug} className="rounded-full border border-blue-100 bg-white px-3 py-2 text-sm font-black text-vector-blue">{text(item.title, locale)}</Link>)}</div></div><div><h2 className="text-2xl font-black text-navy-950">{isChineseSite ? "按典型场景" : "By scenario"}</h2><div className="mt-5 flex flex-wrap gap-2">{businessScenarios.slice(0, 5).map((item) => <Link href="/scenarios" key={item.slug} className="rounded-full border border-slate-200 bg-white px-3 py-2 text-sm font-black text-slate-700">{text(item.title, locale)}</Link>)}</div><Link href="/scenarios" className="mt-5 inline-block text-sm font-black text-vector-blue">{isChineseSite ? "查看全部典型场景" : "View all scenarios"}</Link></div></div></section></main>; }
