import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { JsonLd } from "@/components/json-ld";
import { deliverySteps, text } from "@/lib/content-data";
import { isChineseSite } from "@/lib/site-data";
import { buildPageMetadata, pageBreadcrumbJsonLd } from "@/lib/seo-data";
export const metadata: Metadata = buildPageMetadata({ path: "/delivery-process", title: isChineseSite ? "交付方式" : "Delivery Process", description: isChineseSite ? "从初步沟通到验收维护的七步交付方式。" : "Seven delivery steps from initial conversation to acceptance and maintenance." });
export default function DeliveryProcessPage() { const locale = isChineseSite ? "zh" as const : "en" as const; return <main><JsonLd data={pageBreadcrumbJsonLd(isChineseSite ? "交付方式" : "Delivery Process", "/delivery-process")} /><section className="home-hero text-white"><div className="section-wrap py-16 md:py-20"><p className="kicker kicker-gold">{isChineseSite ? "交付方式" : "DELIVERY PROCESS"}</p><h1 className="mt-5 max-w-4xl text-4xl font-black md:text-6xl">{isChineseSite ? "每一步都可理解、可确认。" : "Every step is understandable and confirmable."}</h1><p className="mt-6 max-w-3xl text-lg leading-9 text-slate-300">{isChineseSite ? "从初步沟通到验收维护，过程围绕范围、原型、测试与交付文档展开。" : "From initial conversation through acceptance and maintenance, the process centers on scope, prototypes, testing and delivery documentation."}</p></div></section><section className="section-wrap py-16"><div className="grid gap-5">{deliverySteps.map((step) => <article key={step.number} className="surface grid gap-5 rounded-lg p-6 md:grid-cols-[90px_1fr_1fr_1fr]"><div><p className="text-sm font-black text-vector-blue">{step.number}</p><h2 className="mt-2 text-xl font-black text-navy-950">{text(step.title, locale)}</h2></div><div><p className="kicker">{isChineseSite ? "客户输入" : "Client input"}</p><p className="mt-2 text-sm leading-6 text-slate-600">{text(step.clientInput, locale)}</p><p className="mt-4 text-xs font-black text-slate-500">{isChineseSite ? "关注点" : "Considerations"}</p><p className="mt-1 text-sm leading-6 text-slate-600">{text(step.risk, locale)}</p></div><div><p className="kicker">OVOPS</p><p className="mt-2 text-sm leading-6 text-slate-600">{text(step.responsibility, locale)}</p></div><div><p className="kicker">{isChineseSite ? "产出与验收" : "Output & acceptance"}</p><p className="mt-2 text-sm leading-6 text-slate-600">{text(step.output, locale)}</p><p className="mt-2 text-sm leading-6 text-slate-600">{text(step.acceptance, locale)}</p></div></article>)}</div><Link href="/solutions" className="button-primary mt-10">{isChineseSite ? "查看解决方案" : "Explore solutions"}<ArrowRight size={16} /></Link></section></main>; }
